--SECUENCIAS DE ID DE TABLAS Correo--
CREATE SEQUENCE sec_cod_correo
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
MINVALUE 1;

--SECUENCIAS DE ID DE TABLAS Prestamo--
CREATE SEQUENCE sec_cod_prestamo
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
MINVALUE 1;

--SECUENCIAS DE ID DE TABLAS TELEFONO--
CREATE SEQUENCE sec_cod_telefono
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
MINVALUE 1;

--SECUENCIAS DE ID DE TABLAS Profesion--
CREATE SEQUENCE sec_id_profesion
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
MINVALUE 1;

--SECUENCIAS DE ID DE TABLAS Distrito--
CREATE SEQUENCE sec_cod_distrito
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
MINVALUE 1;

--SECUENCIAS DE ID DE TABLAS Provincia--
CREATE SEQUENCE sec_cod_provincia
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
MINVALUE 1;

--SECUENCIAS DE ID DE TABLAS Sucursales--
CREATE SEQUENCE sec_cod_sucursal
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
MINVALUE 1;

--SECUENCIAS DE ID DE TABLAS Clientes--
CREATE SEQUENCE sec_id_cliente
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
MINVALUE 1;

--ECUENCIAS DE ID DE TABLAS Prestamo--
CREATE SEQUENCE sec_no_prestamo
INCREMENT BY 100
START WITH 100
MAXVALUE 99999
MINVALUE 100;

--SECUENCIAS DE ID DE TABLAS Transacciones--
CREATE SEQUENCE sec_id_transac
INCREMENT BY 100
START WITH 100
MAXVALUE 99999
MINVALUE 100;


---PARTE II LABORATORIO 7---

--SECUENCIAS DE ID TIPO AHORRO --
CREATE SEQUENCE sec_tipo_aho
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
MINVALUE 1;

--SECUENCIAS DE NUMERO CUENTA AHORRO
CREATE SEQUENCE sec_no_cuenta
INCREMENT BY 100
START WITH 100
MAXVALUE 99999
MINVALUE 100;

--SECUENCIAS DE ID TRANSACCION DEPOSITO RETIRO
CREATE SEQUENCE sec_transacdeporeti
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
MINVALUE 1;

--SECUENCIAS DE AUDITORIA-
CREATE SEQUENCE sec_cod_aut
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
MINVALUE 1;

