--SECUENCIAS DE ID DE TABLAS COLABORADORES--
CREATE SEQUENCE sec_cod_corre
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
MINVALUE 1;

--SECUENCIAS DE ID DE TABLAS COLABORADORES--
CREATE SEQUENCE sec_cod_prestamo
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
MINVALUE 1;

--SECUENCIAS DE ID DE TABLAS COLABORADORES--
CREATE SEQUENCE sec_cod_telefono
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
MINVALUE 1;

--SECUENCIAS DE ID DE TABLAS COLABORADORES--
CREATE SEQUENCE sec_id_profesion
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
MINVALUE 1;

--SECUENCIAS DE ID DE TABLAS COLABORADORES--
CREATE SEQUENCE sec_cod_distrito
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
MINVALUE 1;

--SECUENCIAS DE ID DE TABLAS COLABORADORES--
CREATE SEQUENCE sec_cod_provincia
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
MINVALUE 1;

--SECUENCIAS DE ID DE TABLAS COLABORADORES--
CREATE SEQUENCE sec_cod_sucursal
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
MINVALUE 1;

--SECUENCIAS DE ID DE TABLAS COLABORADORES--
CREATE SEQUENCE sec_id_cliente
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
MINVALUE 1;

--SECUENCIAS DE ID DE TABLAS COLABORADORES--
CREATE SEQUENCE sec_no_prestamo
INCREMENT BY 100
START WITH 100
MAXVALUE 99999
MINVALUE 100;

--SECUENCIAS DE ID DE TABLAS COLABORADORES--
CREATE SEQUENCE sec_id_transac
INCREMENT BY 100
START WITH 100
MAXVALUE 99999
MINVALUE 100;